# Generated by Django 4.1.7 on 2023-03-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_filters', '0002_filteredimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteredimage',
            name='id',
        ),
        migrations.AlterField(
            model_name='filteredimage',
            name='file_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
